### ISSUE TITLE
启动时报错 请问谁有遇到这种问题 how to 解决额

### ISSUE THREAD

**Issue by xiangHannibal** [im-qq/webqq-core#10]
java.lang.ClassCastException: org.apache.http.impl.nio.client.DefaultAsyncRequestDirector cannot be cast to org.apache.http.nio.protocol.HttpAsyncClientExchangeHandler
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.getHandler(HttpAsyncRequestExecutor.java:384)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.exception(HttpAsyncRequestExecutor.java:150)
	at org.apache.http.impl.nio.client.InternalRequestExecutor.exception(InternalRequestExecutor.java:124)
	at org.apache.http.impl.nio.DefaultHttpClientIODispatch.onConnected(DefaultHttpClientIODispatch.java:149)
	at org.apache.http.impl.nio.DefaultHttpClientIODispatch.onConnected(DefaultHttpClientIODispatch.java:51)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.connected(AbstractIODispatch.java:75)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionCreated(BaseIOReactor.java:250)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processNewChannels(AbstractIOReactor.java:429)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:289)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
	at java.lang.Thread.run(Thread.java:722)

**Comment by zhangnew** [comment]
我也遇到了，保证 jar 包版本一致即可
`<commons-lang3.version>3.2</commons-lang3.version>
        <httpcore.version>4.2.2</httpcore.version>
        <httpmime.version>4.2.3</httpmime.version>
        <httpclient.version>4.2.5</httpclient.version>
        <httpasyncclient.version>4.0-beta3</httpasyncclient.version>
        <json.version>20090211</json.version>`
