### ISSUE TITLE
运行错误org/apache/http/config/Lookup

### ISSUE THREAD

**Issue by vodcms** [im-qq/webqq-core#9]
>>>>in MySSLSocketFactory>>
[][2015/05/04 13:40:28.530][WARN][ThreadActorDispatcher:72] QQActor dispatchAction Error!
java.lang.NoClassDefFoundError: org/apache/http/config/Lookup
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_25]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:792) ~[na:1.7.0_25]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_25]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_25]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.7.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.7.0_25]
	at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.createAuthSchemeRegistry(AbstractHttpAsyncClient.java:172) ~[httpasyncclient-4.0-beta3.jar:4.0-beta3]
	at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.getAuthSchemes(AbstractHttpAsyncClient.java:288) ~[httpasyncclient-4.0-beta3.jar:4.0-beta3]
	at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.createHttpContext(AbstractHttpAsyncClient.java:148) ~[httpasyncclient-4.0-beta3.jar:4.0-beta3]
	at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.execute(AbstractHttpAsyncClient.java:515) ~[httpasyncclient-4.0-beta3.jar:4.0-beta3]
	at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.execute(AbstractHttpAsyncClient.java:548) ~[httpasyncclient-4.0-beta3.jar:4.0-beta3]
	at iqq.im.service.ApacheHttpService.executeHttpRequest(ApacheHttpService.java:209) ~[classes/:na]
	at iqq.im.actor.HttpActor.execute(HttpActor.java:62) ~[classes/:na]
	at iqq.im.actor.ThreadActorDispatcher.dispatchAction(ThreadActorDispatcher.java:70) [classes/:na]
	at iqq.im.actor.ThreadActorDispatcher.run(ThreadActorDispatcher.java:82) [classes/:na]
	at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
Caused by: java.lang.ClassNotFoundException: org.apache.http.config.Lookup
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.7.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.7.0_25]
	... 22 common frames omitted

**Comment by im-qq** [comment]
JDK版本问题
